### ISSUE TITLE
yo titpl error

### ISSUE THREAD

**Issue by DouglasHennrich** [SquirrelMobile/generator-titpl#1]
```
? Which template do you need ? (Use arrow keys)
❯ Burger menu 
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/odin/.nvm/versions/node/v4.8.3/lib/node_modules/generator-titpl/app/index.js:55:32
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Socket.<anonymous> (internal/child_process.js:338:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:490:12)
```

**Comment by egenia** [comment]
On which platform are you ? Can you give us node version ?

**Comment by DouglasHennrich** [comment]
`node -v v4.8.3`
`mac os sierra 10.12.6`

**Comment by egenia** [comment]
Try upgrading your node stack.
I am also on mac os sierra, but node v8 and got no problem.

I'll try on older versions. Thanks for feedback

**Comment by DouglasHennrich** [comment]
```
yo titpl
? Which template do you need ? (Use arrow keys)
❯ Burger menu 
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/odin/.nvm/versions/node/v8.4.0/lib/node_modules/generator-titpl/app/index.js:55:32
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
```

still nothing =/
`node -v  v8.4.0`

**Comment by egenia** [comment]
Have you tried upgrading yo version ?
npm install -g yo

**Comment by DouglasHennrich** [comment]
```
npm install -g yo
/Users/odin/.nvm/versions/node/v8.4.0/bin/yo -> /Users/odin/.nvm/versions/node/v8.4.0/lib/node_modules/yo/lib/cli.js
/Users/odin/.nvm/versions/node/v8.4.0/bin/yo-complete -> /Users/odin/.nvm/versions/node/v8.4.0/lib/node_modules/yo/lib/completion/index.js

> yo@2.0.0 postinstall /Users/odin/.nvm/versions/node/v8.4.0/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
+ yo@2.0.0
updated 1 package in 27.658s
```

Still on the same problem =l

**Comment by egenia** [comment]
What happen if you try installing an another generator ?
Like this one : 
npm install -g generator-titaniumburger

Then launch yo and try the 2 generators. Same error for both ?

**Comment by DouglasHennrich** [comment]
```
npm install -g generator-titaniumburger

> spawn-sync@1.0.15 postinstall /Users/odin/.nvm/versions/node/v8.4.0/lib/node_modules/generator-titaniumburger/node_modules/spawn-sync
> node postinstall

+ generator-titaniumburger@0.1.3
added 321 packages in 46.605s
[6:52]➜  Up  yo      
? 'Allo Douglas! What would you like to do? Titaniumburger

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo titaniumburger

? Publisher name: 
     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 


undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/odin/.nvm/versions/node/v8.4.0/lib/node_modules/generator-titaniumburger/app/index.js:47:32
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
```

Some problem with `yo`

**Comment by egenia** [comment]
Other question, when you launch 'yo titpl', the first question is asking you the template you want to start with.
Do you see burger and tab group ?

**Comment by DouglasHennrich** [comment]
![captura de tela 2017-08-28 as 18 55 26](https://user-images.githubusercontent.com/10107024/29795416-80330b90-8c22-11e7-891d-af044d424bfb.png)

**Comment by egenia** [comment]
You use the standard mac os terminal ?

**Comment by DouglasHennrich** [comment]
`zsh` with `oh-my-zsh` plugin but still the mac os terminal

**Comment by egenia** [comment]
I have just tried with zsh without problems.

try an another generator for checking : generator-angular. It is working ?
You run yo as root? If not, try 'sudo yo titpl'

**Comment by DouglasHennrich** [comment]
What's the generator-angular name? so I can download it and test it

**Comment by DouglasHennrich** [comment]
Still the same problem with `sudo yo titpl`

**Comment by egenia** [comment]
nom install -g generator-angular
then launch 'yo' and select angular in the menu

**Comment by DouglasHennrich** [comment]
it works without problem 🤔

**Comment by egenia** [comment]
It comes from generator so. I cannot reproduce your problem. Still checking

**Comment by egenia** [comment]
What does 'titanium sdk list -o json' outputs to you ?

**Comment by DouglasHennrich** [comment]
```shell
{
	"activeSDK": "6.1.2.GA",
	"defaultInstallLocation": "/Users/odin/Library/Application Support/Titanium",
	"installLocations": [
		"/Users/odin/Library/Application Support/Titanium",
		"/Library/Application Support/Titanium"
	],
	"installed": {
		"6.2.0.v20170719160617": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.2.0.v20170719160617",
		"6.1.2.GA": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.1.2.GA",
		"6.1.1.GA": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.1.1.GA",
		"6.0.2.GA": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.0.2.GA",
		"5.5.1.GA": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/5.5.1.GA"
	},
	"sdks": {
		"6.2.0.v20170719160617": {
			"name": "6.2.0.v20170719160617",
			"manifest": {
				"name": "6.2.0.v20170719160617",
				"version": "6.2.0",
				"moduleAPIVersion": {
					"iphone": "2",
					"android": "4",
					"mobileweb": "2",
					"windows": "3"
				},
				"timestamp": "7/19/2017 23:11",
				"githash": "1b3dbc4",
				"platforms": [
					"iphone",
					"android",
					"mobileweb"
				]
			},
			"path": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.2.0.v20170719160617"
		},
		"6.1.2.GA": {
			"name": "6.1.2.GA",
			"manifest": {
				"name": "6.1.2.v20170727160839",
				"version": "6.1.2",
				"moduleAPIVersion": {
					"iphone": "2",
					"android": "3",
					"mobileweb": "2",
					"windows": "3"
				},
				"timestamp": "7/27/2017 23:13",
				"githash": "c4cd761",
				"platforms": [
					"iphone",
					"android",
					"mobileweb"
				]
			},
			"path": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.1.2.GA"
		},
		"6.1.1.GA": {
			"name": "6.1.1.GA",
			"manifest": {
				"name": "6.1.1.v20170626160851",
				"version": "6.1.1",
				"moduleAPIVersion": {
					"iphone": "2",
					"android": "3",
					"mobileweb": "2",
					"windows": "3"
				},
				"timestamp": "6/26/2017 23:13",
				"githash": "c28220a",
				"platforms": [
					"iphone",
					"android",
					"mobileweb"
				]
			},
			"path": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.1.1.GA"
		},
		"6.0.2.GA": {
			"name": "6.0.2.GA",
			"manifest": {
				"name": "6.0.2.v20170224112213",
				"version": "6.0.2",
				"moduleAPIVersion": {
					"iphone": "2",
					"android": "3",
					"mobileweb": "2",
					"windows": "2"
				},
				"timestamp": "2/24/2017 19:26",
				"githash": "3c5806f",
				"platforms": [
					"iphone",
					"android",
					"mobileweb"
				]
			},
			"path": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/6.0.2.GA"
		},
		"5.5.1.GA": {
			"name": "5.5.1.GA",
			"manifest": {
				"name": "5.5.1.v20160927053850",
				"version": "5.5.1",
				"moduleAPIVersion": "2",
				"timestamp": "09/27/16 05:38",
				"githash": "b18727f",
				"platforms": [
					"android",
					"mobileweb",
					"iphone",
					"windows"
				]
			},
			"path": "/Users/odin/Library/Application Support/Titanium/mobilesdk/osx/5.5.1.GA"
		}
	}
}
```

**Comment by DouglasHennrich** [comment]
maybe that's the problem: `titanium sdk list -o json` may it be changed to `appc ti sdk list -o json` ?

**Comment by egenia** [comment]
Your output is good, not coming from here...

Strange problem

**Comment by egenia** [comment]
app.js, line 139, the comma should not be here. Sounds like on your side it is crashing while not on mine. It makes json invalid

**Comment by egenia** [comment]
cd /usr/local/lib/node_modules
nano index.js
go to line 139 and delete the comma

retry yo titpl

**Comment by DouglasHennrich** [comment]
I'm trying to debug it and I'm seeing not output for `stdout`

```
console.log('...');
console.log('sdkList:' + stdout);
console.log('...');
```

**Comment by DouglasHennrich** [comment]
```
...
sdkList:
...
```

**Comment by DouglasHennrich** [comment]
So I guess I found out what's the problem... 
```
exec('appc ti sdk list -o json', function(error, stdout, stderr) {
```
I change the `titanium` for `appc ti` since I don't have `titanium-cli` installed

**Comment by DouglasHennrich** [comment]
maybe you have to do some verification with the user has `titanium-cli` otherwise use the `appc-cli`

**Comment by egenia** [comment]
thx for feedback Douglas

**Comment by DouglasHennrich** [comment]
Thanks for helping me found out :D

**Comment by bruce-atkinson** [comment]
Just to be clear for other users trying to fix this, go to:
`/usr/local/lib/node_modules/generator-titpl/app/index.js`
and edit line 54 changing:
`exec('titanium sdk list -o json', function(error, stdout, stderr) {`
into
`exec('appc ti sdk list -o json', function(error, stdout, stderr) {`
